# Generated by Django 2.0.4 on 2018-05-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselfigure',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        #migrations.RemoveField(model_name='goal',name='supMoney',),
        migrations.AddField(
            model_name='goal',
            name='minSupMoney',
            field=models.FloatField(default=0.0, verbose_name='最小支持金额'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='supMoney',
            field=models.FloatField(default=0.0, verbose_name='支持金额'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='clock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='goals.Clock', verbose_name='打卡记录'),
        ),
    ]
