# Generated by Django 2.0.4 on 2018-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20180524_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='目标海报'),
        ),
    ]
