# Generated by Django 2.0.4 on 2018-05-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goal_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='poster_template',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='目标海报模板'),
        ),
    ]
