# Generated by Django 2.0.4 on 2018-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_poster_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselfigure',
            name='img',
            field=models.ImageField(upload_to='carousel/', verbose_name='上传图片'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='目标海报'),
        ),
    ]
