# Generated by Django 2.0.5 on 2018-07-18 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20180525_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户姓名')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='登录时间')),
                ('login_ip', models.GenericIPAddressField(verbose_name='登录IP')),
            ],
            options={
                'verbose_name': '用户登录信息',
                'verbose_name_plural': '用户登录信息',
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, verbose_name='敏感词')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '敏感词过滤',
                'verbose_name_plural': '敏感词过滤',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='clock_num',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='打卡次数'),
        ),
        migrations.AddField(
            model_name='goal',
            name='poster_result',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='结果海报'),
        ),
        migrations.AddField(
            model_name='goal',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='二维码'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.Goal', verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='trade_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockTime',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='goals.Goal', verbose_name='目标'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='operateType',
            field=models.CharField(choices=[('refund', '退款'), ('withdrawCash', '提现'), ('pay', '支付'), ('income', '收入')], default='pay', help_text="'pay':u'支付','withdrawCash': u'提现','refund':u'退款','income':u'收入'", max_length=15, verbose_name='操作类型'),
        ),
    ]
